### PR TITLE
Allow configurable URL

### PR DESCRIPTION
**Pull request by signedbit**
Hi Nicolas, without a configurable URL, this fork can't be used with BTCPay Server. Refactored a little, but maintained full backwards compatibility. Edits were made to be unlikely to create merge conflicts in future. Added tests and ran existing tests.

Merge #1 first so diff is smaller.

Thanks.

### CODE REVIEW

**Review by Kukks — CHANGES_REQUESTED** [review]
Thanks for the PR! Something glitched on Github and the diff still shows the full commit from before.  

I diffed your branch locally against master and reviewed it there though.

One thing I found was that you added the following todo. Is it essential for this PR to be merged?
```
 // TODO: write to parsed EnvConfig
```

**Comment by signedbit** [comment]
Hi Kukks, thanks for quick review. Tried rebasing after merge but "Everything up-to-date." Strange.

The TODO is not essential to merge. There are now two parallel data structures, the JsonNode and the new EnvConfig object. The only remaining difference is the JsonNode is still used by the token cache. I will refactor the token cache to use EnvConfig and remove the JsonNode within a day or two.

**Comment by signedbit** [comment]
Took care of the TODO. 

NB There are now two parallel data structures, the JsonNode and the new EnvConfig object. Both are kept in sync. Future maintainers can use the proper EnvConfig object. Removing the JsonNode completely could cause merge conflicts in the future when syncing with upstream. I'm a volunteer, need to reduce maintenance time required.

**Comment by signedbit** [comment]
Hi Kukks, I sat down and fixed the git history. Now it's quick and easy to review. Thanks in advance.

**Review by Kukks — APPROVED** [review]

**Comment by Kukks** [comment]
Thanks, merged!

**Pull request merged**
